-- Le Chariot — Migration v22
-- Das Gebiet ist die Identität einer Anforderung, nicht die Ankerfiliale
--
-- ============================================================
-- Das Problem
-- ============================================================
--
-- `market_id` ist seit v19 der Primärschlüssel von `area_requests`. Damit kann
-- eine Filiale genau EINE offene Anforderung tragen — und zwei Orte können
-- denselben nächsten Anker haben. Im gemeldeten Fall vom 2026-07-30 ist genau
-- das so: Penny Am Haff ist die nächste Filiale sowohl für Ueckermünde als
-- auch für Ahlbeck, 24,5 km über das Haff.
--
-- Wer zweiter kommt, bekommt 409. Die App weicht seit v21 auf den
-- zweitnächsten Anker aus, wenn die vorhandene Zeile Koordinaten aus einer
-- anderen Rasterzelle trägt. Das deckt den gemeldeten Fall — es deckt NICHT
-- den Fall, dass alle Anker einer Region schon fremd belegt sind. Dann geht
-- die Anforderung **still** nicht raus.
--
-- „Still nicht rausgegangen" ist die Fehlerklasse, die dieses Projekt inzwischen
-- dreimal bezahlt hat: die v19-Policy, das fehlende `LIDL_SOURCE` in
-- `branches.yml`, und die Anker-PLZ selbst. Sie hat jedes Mal dieselbe Form —
-- nichts schlägt fehl, es passiert nur nichts.
--
-- ============================================================
-- Die Korrektur
-- ============================================================
--
-- Der Anker ist ein **Existenzbeweis**, kein Schlüssel. Was eine Anforderung
-- identifiziert, ist das GEBIET. Also:
--
--   * ein Surrogatschlüssel `id` als Primärschlüssel,
--   * `market_id` bleibt als gewöhnliche Spalte (weiterhin gegen `branches`
--     geprüft — die Lehre aus der Phantom-PLZ 94108 gilt unverändert),
--   * und ein UNIQUE über die Rasterzelle `area_key`.
--
-- Damit gilt beides gleichzeitig, und das ist der ganze Zweck:
--   * zwei Zeilen für denselben Anker in VERSCHIEDENEN Zellen sind möglich,
--   * zwei Zeilen in DERSELBEN Zelle fallen zusammen — das ist die Aufgabe des
--     Cooldowns, und die soll er behalten.
--
-- `area_key` ist dieselbe Zeichenkette, auf die `area_dispatch_log` seit v21
-- schlüsselt (`cell:53.9,14.2`, sonst `plz:17419`), und dieselbe, die
-- `branches::area_cell` im Rust-Backend erzeugt. Drei Stellen, eine Regel —
-- laufen sie auseinander, holt ein Lauf ein Gebiet doppelt oder gar nicht.
--
-- Idempotent — kann gefahrlos erneut laufen.

-- ============================================================
-- 1) Surrogatschlüssel
-- ============================================================
--
-- `generated by default`, nicht `always`: Der Backfill unten und ein etwaiges
-- Wiedereinspielen alter Zeilen dürfen eine ID mitbringen.
alter table public.area_requests
    add column if not exists id bigint generated by default as identity;

do $$
begin
  -- Den alten Primärschlüssel nur lösen, wenn er noch auf market_id steht.
  if exists (
    select 1
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name = tc.constraint_name
       and kcu.table_schema = tc.table_schema
     where tc.table_schema = 'public'
       and tc.table_name = 'area_requests'
       and tc.constraint_type = 'PRIMARY KEY'
       and kcu.column_name = 'market_id'
  ) then
    alter table public.area_requests drop constraint area_requests_pkey;
    alter table public.area_requests add constraint area_requests_pkey primary key (id);
  end if;
end
$$;

-- `market_id` bleibt Pflicht und bleibt geprüft — es ist weiterhin das
-- Einzige, was sich hart gegen `branches` halten lässt.
alter table public.area_requests alter column market_id set not null;

-- ============================================================
-- 2) Der Gebietsschlüssel
-- ============================================================
--
-- Abgeleitet, nie vom Client benannt — dieselbe Regel wie bei `plz`. Der
-- BEFORE-Trigger setzt ihn, die Spaltenrechte lassen ihn gar nicht erst zu.
alter table public.area_requests
    add column if not exists area_key text;

comment on column public.area_requests.area_key is
    'Rasterzelle der Anforderung (cell:<lat>,<lon> auf 0,1 Grad gerundet), '
    'sonst plz:<plz>. Vom BEFORE-Trigger gesetzt, nie vom Client. '
    'UNIQUE: ein Gebiet, eine offene Anforderung.';

-- Bestandszeilen nachziehen, mit exakt der Formel des Triggers.
update public.area_requests
   set area_key = case
         when lat is not null and lon is not null
           then 'cell:' || round(lat::numeric, 1) || ',' || round(lon::numeric, 1)
         when plz is not null then 'plz:' || plz
         else null
       end
 where area_key is null;

-- Am 2026-07-31 gegen die Live-Tabelle geprüft: 6 Zeilen, 6 verschiedene
-- Schlüssel, keine Kollision. Der Index kann also ohne Aufräumen entstehen.
-- `null` bleibt erlaubt und kollidiert nicht mit sich selbst (Postgres zählt
-- NULLs im Unique-Index als verschieden) — eine Zeile ohne Gebiet UND ohne
-- Koordinaten ist ohnehin keine Anforderung, die je losläuft.
create unique index if not exists area_requests_area_key_uniq
    on public.area_requests (area_key)
    where area_key is not null;

-- ============================================================
-- 3) Spaltenrechte: unverändert eng
-- ============================================================
--
-- Weder `id` noch `area_key` gehören dazu. Der Zweischritt ist derselbe wie in
-- v19/v21 und damit idempotent.
revoke insert on public.area_requests from anon, authenticated;
grant  insert (market_id, lat, lon) on public.area_requests to anon, authenticated;

-- ============================================================
-- 4) BEFORE INSERT: zusätzlich den Gebietsschlüssel setzen
-- ============================================================
--
-- Unverändert aus v21 übernommen, bis auf die letzte Zuweisung. Die
-- Reihenfolge ist wichtig: Der Schlüssel entsteht ERST, nachdem die
-- Koordinaten geprüft (und gegebenenfalls verworfen) wurden — sonst trüge eine
-- Zeile mit unplausibler Lage einen Zellenschlüssel, den es nicht geben darf.
create or replace function public.area_request_resolve_plz()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  anchor_lat  double precision;
  anchor_lon  double precision;
  gap_km      double precision;
begin
  select b.plz, b.lat, b.lon
    into new.plz, anchor_lat, anchor_lon
  from public.branches b
  where b.market_id = new.market_id;

  if new.lat is null or new.lon is null then
    new.lat := null;
    new.lon := null;
  elsif new.lat not between 47.0 and 56.0
     or new.lon not between 5.0 and 16.0 then
    raise notice 'area_request_resolve_plz: %/% liegt nicht in Deutschland, Koordinaten verworfen',
      new.lat, new.lon;
    new.lat := null;
    new.lon := null;
  else
    gap_km := public.haversine_km(new.lat, new.lon, anchor_lat, anchor_lon);
    if gap_km is null then
      raise notice 'area_request_resolve_plz: Anker % ohne Koordinaten, Client-Position ungeprueft uebernommen',
        new.market_id;
    elsif gap_km > 60.0 then
      raise notice 'area_request_resolve_plz: %/% liegt % km vom Anker % — Koordinaten verworfen',
        new.lat, new.lon, round(gap_km::numeric, 1), new.market_id;
      new.lat := null;
      new.lon := null;
    end if;
  end if;

  -- Erst jetzt, mit geprüfter Lage.
  new.area_key := case
    when new.lat is not null and new.lon is not null
      then 'cell:' || round(new.lat::numeric, 1) || ',' || round(new.lon::numeric, 1)
    when new.plz is not null then 'plz:' || new.plz
    else null
  end;

  return new;
end;
$$;

revoke execute on function public.area_request_resolve_plz() from public, anon, authenticated;

drop trigger if exists on_area_request_resolve on public.area_requests;
create trigger on_area_request_resolve
  before insert on public.area_requests
  for each row
  execute function public.area_request_resolve_plz();

-- ============================================================
-- 5) Dispatch: den Schlüssel benutzen statt ihn nachzubauen
-- ============================================================
--
-- Der Rest ist Wort für Wort v21. Einzige Änderung: `dispatch_key` wird nicht
-- mehr aus lat/lon zusammengesetzt, sondern ist `new.area_key` — dieselbe
-- Zeichenkette, die jetzt auch die Zeile identifiziert. Damit können Cooldown
-- und Unique nicht mehr auseinanderlaufen.
create or replace function public.trigger_area_scrape()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, net, vault
as $$
declare
  pat            text;
  last_dispatch  timestamptz;
  dispatch_key   text;
begin
  if new.last_synced is not null then
    return new;
  end if;

  dispatch_key := new.area_key;

  if dispatch_key is null then
    raise warning 'trigger_area_scrape: Filiale % hat weder PLZ noch Koordinaten, kein Gebiets-Lauf',
      new.market_id;
    return new;
  end if;

  select last_dispatch_at into last_dispatch
  from public.area_dispatch_log
  where area_key = dispatch_key;

  if last_dispatch is not null
     and last_dispatch > now() - interval '30 minutes' then
    raise notice 'trigger_area_scrape: Gebiet % vor % dispatcht (< 30 min Cooldown), uebersprungen',
      dispatch_key, now() - last_dispatch;
    return new;
  end if;

  select decrypted_secret into pat
  from vault.decrypted_secrets
  where name = 'github_pat';

  if pat is null then
    raise warning 'trigger_area_scrape: Vault secret github_pat missing, no run dispatched for area %',
      dispatch_key;
    return new;
  end if;

  perform net.http_post(
    url := 'https://api.github.com/repos/Scxttk/lechariot-backend/actions/workflows/branches.yml/dispatches',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || pat,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'lechariot-supabase-trigger',
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object(
      'ref', 'master',
      'inputs', jsonb_build_object(
        'area',          coalesce(new.plz, ''),
        'skip_national', 'true',
        'lat',           coalesce(new.lat::text, ''),
        'lon',           coalesce(new.lon::text, ''),
        'anchor',        new.market_id
      )
    )
  );

  insert into public.area_dispatch_log (area_key, last_dispatch_at)
  values (dispatch_key, now())
  on conflict (area_key) do update set last_dispatch_at = excluded.last_dispatch_at;

  return new;
exception when others then
  raise warning 'trigger_area_scrape: dispatch failed for area %: %', dispatch_key, sqlerrm;
  return new;
end;
$$;

revoke execute on function public.trigger_area_scrape() from public, anon, authenticated;

drop trigger if exists on_area_request_insert on public.area_requests;
create trigger on_area_request_insert
  after insert on public.area_requests
  for each row
  execute function public.trigger_area_scrape();

-- ============================================================
-- Was der Lauf jetzt anders machen MUSS
-- ============================================================
--
-- `mark_area_resolved` trug die aufgelöste PLZ bisher über `market_id` ein.
-- Ein Anker kann ab jetzt mehrere Zeilen tragen, und die gehören verschiedenen
-- Orten — die PLZ des gelaufenen Gebiets auf alle zu schreiben, wäre genau der
-- Fehler, den v21 abgeschafft hat, nur andersherum. Der Lauf filtert deshalb
-- über `area_key`, sobald er Koordinaten hat. Steht im selben PR.
--
-- ============================================================
-- Was die APP jetzt anders machen muss
-- ============================================================
--
-- Sie fragte ihre offene Anforderung über `market_id` ab und nahm die erste
-- Zeile. Bei mehreren Zeilen je Anker ist „die erste" beliebig. Ab v22 ist der
-- Schlüssel das Gebiet, also fragt sie über `area_key`. Der Ausweichweg auf den
-- zweitnächsten Anker aus v21 wird damit überflüssig und fällt weg — er war
-- die Krücke für genau diesen Primärschlüssel. Eigener PR im App-Repo.
--
-- ============================================================
-- Gegenprobe nach dem Ausführen
-- ============================================================
-- Es gibt KEINE Testinfrastruktur für Migrationen — kein pgTAP, kein lokales
-- Postgres, keine Supabase-CLI. Diese Liste ist das einzige Tor.
--
-- Punkte 1-4 im SQL-Editor, 5-9 mit curl und dem PUBLISHABLE Key (nicht dem
-- Service-Key — mit dem greift keine einzige Policy und die Probe wäre wertlos).
--
-- 1) Struktur:
--    select column_name, data_type, is_nullable
--      from information_schema.columns
--     where table_schema='public' and table_name='area_requests'
--     order by ordinal_position;
--    -- erwartet: id (bigint, NO), market_id (text, NO), area_key (text, YES)
--
--    select tc.constraint_type, kcu.column_name
--      from information_schema.table_constraints tc
--      join information_schema.key_column_usage kcu
--        on kcu.constraint_name = tc.constraint_name
--     where tc.table_schema='public' and tc.table_name='area_requests'
--       and tc.constraint_type='PRIMARY KEY';
--    -- erwartet: PRIMARY KEY auf id, NICHT auf market_id
--
-- 2) Bestandszeilen haben den Umbau überlebt — das ist der Punkt, an dem eine
--    kaputte Migration auffällt, und dort stehen die Zeilen von gestern Nacht,
--    darunter die von Scotts Bruder:
--    select id, market_id, plz, lat, lon, area_key, last_synced
--      from public.area_requests order by id;
--    -- erwartet: jede Zeile mit id und area_key, Rest unverändert
--    -- erwartet: 4030423 -> cell:53.9,14.2   (Ahlbeck)
--    --           4030191 -> plz:17373        (ohne Koordinaten)
--
-- 3) Der Unique greift, und zwar auf dem Gebiet:
--    select indexname, indexdef from pg_indexes
--     where schemaname='public' and tablename='area_requests';
--    -- erwartet: area_requests_area_key_uniq über (area_key)
--
-- 4) Spaltenrechte — weiterhin genau drei, ohne id und area_key:
--    select column_name, privilege_type from information_schema.column_privileges
--     where table_schema='public' and table_name='area_requests'
--       and grantee='anon' and privilege_type='INSERT';
--    -- erwartet: market_id, lat, lon
--
-- 5) DER KERNFALL — derselbe Anker, zwei Orte. Beide müssen durchkommen.
--    Anker aus Ueckermünde (4030191), einmal mit Ueckermünder, einmal mit
--    Ahlbecker Koordinaten:
--    curl -i -X POST "$SUPABASE_URL/rest/v1/area_requests" \
--      -H "apikey: $ANON_KEY" -H "Authorization: Bearer $ANON_KEY" \
--      -H "Content-Type: application/json" \
--      -d '{"market_id":"4030191","lat":53.7383,"lon":14.0511}'
--    -- erwartet: 201
--    ... -d '{"market_id":"4030191","lat":53.9440,"lon":14.1830}'
--    -- erwartet: 201  <- VOR v22 war das ein 409, und genau daran hing alles
--    select id, market_id, lat, lon, area_key from public.area_requests
--     where market_id='4030191' order by id;
--    -- erwartet: zwei Zeilen, area_key cell:53.7,14.1 und cell:53.9,14.2
--
-- 6) Dieselbe Zelle fällt weiterhin zusammen (das bleibt Aufgabe des Cooldowns):
--    ... -d '{"market_id":"4030191","lat":53.9445,"lon":14.1835}'
--    -- erwartet: 409 (duplicate key area_requests_area_key_uniq)
--    --           Die App wertet 409 seit v19 als „laeuft schon".
--
-- 7) Der Dispatch wurde ANGENOMMEN, nicht mit 422 geschluckt:
--    select id, status_code, left(content,200) as content, created
--      from net._http_response order by created desc limit 3;
--    -- erwartet: 204
--
-- 8) Steuerspalten mitgeschickt — jeweils „permission denied for column":
--    ... -d '{"market_id":"4030191","plz":"17419"}'
--    ... -d '{"market_id":"4030191","area_key":"cell:0.0,0.0"}'
--    ... -d '{"market_id":"4030191","id":1}'
--
-- 9) Aufraeumen (Service-Rechte):
--    delete from public.area_requests where market_id='4030191' and last_synced is null;
--    delete from public.area_dispatch_log;
